backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - file: "src/data/socials/data.json"
        label: "Socials"
        name: "socials"
        fields:
          - {label: Socials, name: socials, widget: list, fields: [{label: Image, name: image, widget: image}, {label: URL, name: url, widget: string}]}
      - file: "src/data/navigation/data.json"
        label: "Navigation"
        name: "navigation"
        fields:
          - {label: "Header", name: "header", widget: "object", fields: [{label: "Display", name: "display", widget: "object", fields: [{label: "Show Blog", name: "showBlog", widget: "boolean"},{label: "Show Contact", name: "showContact", widget: "boolean"}]},{label: "Labels", name: "labels", widget: "object", fields: [{label: "Shop", name: "shop", widget: "string"},{label: "Info", name: "info", widget: "string"},{label: "Blog", name: "blog", widget: "string"},{label: "Contact", name: "contact", widget: "string"}]}]}
          - {label: "Footer", name: "footer", widget: "list", fields: [{label: "Column Label", name: "columnLabel", widget: "string"},{label: "Links", name: "links", widget: "list", fields: [{label: "Path", name: "path", widget: "string"},{label: "Label", name: "label", widget: "string"}]}]}

  - name: "landingPage"
    label: "Landing Page"
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Page Content"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Hero Banner", name: "heroBanner", widget: object, fields: [{label: Image, name: image, widget: image},{label: Hero Left, name: heroLeft, widget: object, fields: [{label: Label, name: label, widget: string},{label: Collection, name: collection, widget: collectionSelect}]},{label: Hero Right, name: heroRight, widget: object, fields: [{label: Label, name: label, widget: string},{label: Collection, name: collection, widget: collectionSelect}]}]}
          - {label: "Featured Collections", name: "featuredCollections", widget: list, field: {label: "Collection", name: "collection", widget: "collectionSelect"}}

  - name: "infoPages"
    label: "Info Pages"
    folder: "src/pages/info"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  