backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: "src/data/socials/data.json"
        label: "Socials"
        name: "socials"
        fields:
          - {label: Socials, name: socials, widget: list, fields: [{label: Image, name: image, widget: image}, {label: URL, name: url, widget: string}]}
      - file: "src/data/currencies/data.json"
        label: "Currencies"
        name: "currencies"
        fields:
          - {label: Currencies, name: currencies, widget: list, fields: [{label: Code, name: code, widget: string}, {label: Symbol, name: symbol, widget: string}]}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  
  - name: "info"
    label: "Info"
    folder: "src/pages/info"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Hero Banner", name: "heroBanner", widget: object, fields: [{label: Image, name: image, widget: image},{label: Hero Left, name: heroLeft, widget: object, fields: [{label: Label, name: label, widget: string},{label: Collection, name: collection, widget: collectionSelect}]},{label: Hero Right, name: heroRight, widget: object, fields: [{label: Label, name: label, widget: string},{label: Collection, name: collection, widget: collectionSelect}]}]}
          - {label: "Featured Collections", name: "featuredCollections", widget: list, fields: [
              {label: "Collection", name: "collection", widget: "collectionSelect"}
            ]}
      # - file: "src/pages/about/index.md"
      #   label: "About"
      #   name: "about"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      #     - {label: "Title", name: "title", widget: "string"}
      #     - {label: "Body", name: "body", widget: "markdown"}
      # - file: "src/pages/shop/index.md"
      #   label: "Products Page"
      #   name: "shop"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
      #     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      #     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      #     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      #     - {label: Full_image, name: full_image, widget: image}
      #     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
